#!/bin/bash

list() {
    local ids=()
    mapfile -t ids < <(ss --no-header --ipv4 --tcp 'sport = :28772' | awk '{print $5}')   # Récupération des adresses IP des clients
    echo "Found ${#ids[@]} client(s) :"
    for id in "${ids[@]}"; do {
    # Affichage des adresses IP des clients
        echo "  > $id"
    } done
}

sync() {
    mapfile -t pid < <(pgrep -f -o ./smalldb)       # Récupération du pid de l'exécutable du serveur
    echo "Sync SmallDB..."
    kill -s USR1 "$pid"     # Envoi du signal
}

stop() {
    mapfile -t pid < <(pgrep -f -o ./smalldb)       # Récupération du pid de l'exécutable du serveur
    echo "Stoping SmallDB..."
    kill -s SIGINT "$pid"       # Envoi du signal
}

RED=$'\e[1;31m'
ENDCOLOR=$'\033[0m'
if [ -n "$1" ]; then {
    if [ "$1" = 'list' ] || [ "$1" = 'sync' ] || [ "$1" = 'stop' ]; then {
        if [ "$1" = 'list' ]; then {         # Gestion de la commande 'list'
            list
        } elif [ "$1" = 'sync' ]; then {           # Gestion de la commande 'sync'
            sync
        } elif [ "$1" = 'stop' ]; then {           # Gestion de la commande 'stop'
            stop 
        } fi
    } else {
        echo "$RED ERROR : unknown command $ENDCOLOR" 1>&2 
    } fi
} else {
    echo "$RED ERROR : no command written $ENDCOLOR" 1>&2 
} fi